apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
    cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: automation-mgmt-eks
    devEnvApprovers:
    - jenkinsxbotmo
    environmentGitOwner: Morgan-Jenkins-X
    environmentGitPublic: true
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "339337551661"
    provider: eks
    region: us-east-2
    registry: 339337551661.dkr.ecr.us-east-2.amazonaws.com
  environments:
  - key: dev
    owner: Morgan-Jenkins-X
    repository: automation-mgmt-eks
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: vault
  vault: {}
  webhook: lighthouse
