apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: automation-mgmt-eks
    environmentGitOwner: Morgan-Jenkins-X
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "339337551661"
    provider: eks
    region: us-east-2
    registry: 339337551661.dkr.ecr.us-east-2.amazonaws.com
  environments:
  - key: dev
    owner: Morgan-Jenkins-X
    repository: jx3-eks-vault
  - key: staging
  - key: production
  ingress:
    domain: ""
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: jenkinsxbotmo
  repository: nexus
  secretStorage: secretsManager
  # storage:
  # - name: logs
  #   url: s3://logs-automation-mgmt-eks-20220801214725586400000003
  # - name: reports
  #   url: s3://reports-automation-mgmt-eks-20220801214725593100000005
  # - name: repository
  #   url: s3://repository-automation-mgmt-eks-20220801214725593400000006
  terraform: true
  vault: {}
  webhook: lighthouse
