apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: automation-mgmt-eks
    environmentGitOwner: Morgan-Jenkins-X
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "339337551661"
    provider: eks
    region: us-east-2
    registry: 339337551661.dkr.ecr.us-east-2.amazonaws.com
  environments:
  - key: dev
    owner: Morgan-Jenkins-X
    repository: jx3-eks-vault
  - key: staging
  - key: production
  ingress:
    domain: ""
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: jenkinsxbotmo
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-automation-mgmt-eks-20220802211323229900000001
  - name: reports
    url: s3://reports-automation-mgmt-eks-20220802211323249800000002
  - name: repository
    url: s3://repository-automation-mgmt-eks-20220802211323316600000005
  terraform: true
  vault:
    aws:
      dynamoDBRegion: us-east-2
      dynamoDBTable: vault-unseal-automation-mgmt-eks-oEiP3NFT
      kmsKeyId: d2a33c9c-c409-4fe7-b444-c0968deb90a4
      kmsRegion: us-east-2
      s3Bucket: vault-unseal-automation-mgmt-eks-20220802211323254800000003
      s3Region: us-east-2
  webhook: lighthouse
